// src/components/islands/CampoDemo.svelte
<script>
  import { onMount } from 'svelte';

  let el;
  let valor = 0;

  onMount(() => {
    const onChange = (e) => (valor = e.detail.value);
    el.addEventListener('change', onChange);
    return () => el.removeEventListener('change', onChange);
  });
</script>

<div style="display:flex; align-items:center; gap:16px">
  <campo-numerico bind:this={el} value="0">Número:</campo-numerico>
  <code style="font-family: ui-monospace, monospace; font-size:13px">
    Svelte lee: {valor}
  </code>
</div>

// src/components/islands/CampoDemo.jsx
import { useEffect, useRef, useState } from 'react';

export default function CampoDemo() {
  const ref = useRef(null);
  const [valor, setValor] = useState(0);

  useEffect(() => {
    const el = ref.current;
    const onChange = (e) => setValor(e.detail.value);
    el.addEventListener('change', onChange);
    return () => el.removeEventListener('change', onChange);
  }, []);

  return (
    <div style={{ display: 'flex', alignItems: 'center', gap: 16 }}>
      <campo-numerico ref={ref} value="0">Número:</campo-numerico>
      <code style={{ fontFamily: 'ui-monospace, monospace', fontSize: 13 }}>
        React lee: {valor}
      </code>
    </div>
  );
}
